/* Shared learner controls. Recognition agreement is not a pronunciation assessment. */
(()=>{'use strict';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFC').toLowerCase().replace(/[^a-z가-힣ㄱ-ㅎㅏ-ㅣ0-9]/g,'');
function align(a,b){const d=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)d[i][0]=i;for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]!==b[j-1]));let i=a.length,j=b.length,out=[];while(i||j){if(i&&j&&d[i][j]===d[i-1][j-1]+(a[i-1]!==b[j-1])){out.push([a[--i],b[--j]]);}else if(i&&d[i][j]===d[i-1][j]+1)out.push([a[--i],'']);else out.push(['',b[--j]]);}return {distance:d[a.length][b.length],pairs:out.reverse()};}
const score=(a,b)=>{a=norm(a);b=norm(b);return a&&b?Math.round(100*(1-align(a,b).distance/Math.max(a.length,b.length))):0;};
function feedback(target,heard,lang,tip){const a=norm(target),b=norm(heard),r=align(a,b),same=a===b&&!!a;const row=n=>r.pairs.map(p=>'<span class="'+(p[0]===p[1]?'speechOk':'speechDiff')+'">'+escape(p[n]||'□')+'</span>').join('');let advice=tip||'お手本を短く区切って聞き、同じリズムでまねしましょう。';if(lang==='ko'&&!tip){if(/합니다|습니다/.test(target))advice='練習のコツ：「니다」の前は唇を閉じる「ム」。母音を足さず次へ。';else if(/주세요/.test(target))advice='練習のコツ：「주」は唇を丸めて。お手本で音のつながりを確認。';else advice='練習のコツ：カタカナより音を優先。短く区切ってまねしましょう。';}return '<div class="speechCompare"><div><b>お手本</b> '+row(0)+'</div><div><b>聞き取り</b> '+(b?row(1):'聞き取れませんでした')+'</div><div>'+ (same?'✓ 文字は一致。次は見ないで言ってみましょう。':'赤字：違って認識された箇所。そこだけ聞いて再挑戦。')+'</div><div>'+escape(advice)+'</div><small>認識一致は文字の比較です。発音・抑揚の正確さや、実際に通じるかは判定していません。</small></div>';}
function getFlow(lang){try{return localStorage.getItem(lang+'LearningFlow')==='manual'?'manual':'auto'}catch{return'auto'}}
function setFlow(lang,value){try{localStorage.setItem(lang+'LearningFlow',value)}catch{}}
function traceFeedback(canvas,char){const context=canvas.getContext('2d'),ink=context.getImageData(0,0,canvas.width,canvas.height).data;let count=0;for(let i=3;i<ink.length;i+=4)if(ink[i]>40)count++;if(count<70)return{pass:false,text:'線がまだ少ないようです。見本を見ながら書きましょう。'};const mask=document.createElement('canvas');mask.width=canvas.width;mask.height=canvas.height;const c=mask.getContext('2d');c.font='900 145px system-ui';c.textAlign='center';c.textBaseline='middle';c.fillText(char,mask.width/2,mask.height/2);const target=c.getImageData(0,0,mask.width,mask.height).data;let total=0,covered=0,near=0;const w=mask.width,h=mask.height;function nearby(data,x,y){for(let dy=-9;dy<=9;dy+=3)for(let dx=-9;dx<=9;dx+=3){let xx=x+dx,yy=y+dy;if(xx>=0&&xx<w&&yy>=0&&yy<h&&data[(yy*w+xx)*4+3]>40)return true;}return false;}for(let y=0;y<h;y+=2)for(let x=0;x<w;x+=2){let i=(y*w+x)*4+3;if(target[i]>40){total++;if(nearby(ink,x,y))covered++;}if(ink[i]>40&&nearby(target,x,y))near++;}const coverage=covered/Math.max(total,1),precision=near/Math.max(count/4,1),pass=coverage>.55&&precision>.5;return{pass,text:pass?'○ 見本に近い形です。次の文字も練習できます。（形の目安判定）':coverage<.55?'見本の線が足りない箇所を確認して、もう一度。（形の目安判定）':'線の位置・大きさを見本に近づけましょう。（形の目安判定）'};}
window.LearningTools={escape,norm,align,score,feedback,getFlow,setFlow,traceFeedback};})();
